### ISSUE TITLE
Consider caching sqlx-cli on ci worflows

### ISSUE THREAD

**Issue by pedromfedricci** [LukeMathWalker/zero-to-production#111]
The current step to install sqlx-cli with cargo will download/compile the binary every job run, which takes a considerable amount of time. Since the binary is the same in each run, it could be cached with actions/cache, based on the desired version and features as key. Changes that could be made for each job that uses sqlx-cli are the following:

1) Add two job level environment variables:
```yaml
env:
  # ...
  SQLX_VERSION: 0.5.5
  SQLX_FEATURES: postgres
```
2) Add cache step for sqlx-cli, bases on version and features:
```yaml
steps:
  # ...
  - name: Cache sqlx-cli
    uses: actions/cache@v2
    id: cache-sqlx
      with:
        path: |
          ~/.cargo/bin/sqlx
        key: ${{ runner.os }}-sqlx-${{ env.SQLX_VERSION }}-${{ env.SQLX_FEATURES }}
```
3) Conditionally installs sqlx-cli if cache misses:
```yaml
steps:
  # ...
  # name: Cache sqlx-cli
  # ...
  - name: Install sqlx-cli 
    uses: actions-rs/cargo@v1
    if: steps.cache-sqlx.outputs.cache-hit == false
    with:
      command: install 
      args: >
        sqlx-cli
        --force
        --version=${{ env.SQLX_VERSION }}
        --features=${{ env.SQLX_FEATURES }}
        --no-default-features
        --locked
```
Cuts off 4~5 min from the CI workflow run, helps a lot going through the book.
What do you think? Would you be interested in reviewing a PR?
ty!
