### ISSUE TITLE
zld archived

### ISSUE THREAD

**Issue by JonasKs** [LukeMathWalker/zero-to-production#192]
https://github.com/michaeleisel/zld 

Seems like this should be replaced with `lld` for macOS now.

**Comment by JonasKs** [comment]
```toml
# On MacOS, `brew install llvm` and fix .zshrc
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
```

This worked for me. `brew install llvm` + following the instructions given by `brew info llvm`.

**Comment by JonasKs** [comment]
Nvm, this did not work when running `test` etc. through Intellij. 

This did, how ever:
```toml
# On MacOS, `brew install llvm` and fix .zshrc
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]
```

<img width="949" alt="image" src="https://user-images.githubusercontent.com/5310116/224564540-dd9dadf5-6a0d-403f-bf4d-33dd634f43d5.png">

Also works in terminal.

**Comment by sondrelg** [comment]
My intel macbook needed - you're on arch right @JonasKs?

```
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
```

**Comment by JonasKs** [comment]
M1, yeah. The setup you use works through terminal for me, but not through PyCharm. 

Under "[Using LLD](https://lld.llvm.org/MachO/index.html#using-lld )" pointing to `lld64.lld` seem to be the documented path as well: 

> LLD can be used by adding -fuse-ld=/path/to/ld64.lld to the linker flags. For Xcode, this can be done by adding it to “Other linker flags” in the build settings. For Bazel, this can be done with --linkopt or with [rules_apple_linker](https://github.com/keith/rules_apple_linker).

**Comment by LukeMathWalker** [comment]
I think the path where `lld64` is installed by `homebrew` might be different on M1 vs x86_64 macs.

**Comment by sondrelg** [comment]
The lld64.lld failed for me at least 👍

**Comment by JonasKs** [comment]
So this should solve it for both? 😊 
```toml
# On MacOS, `brew install llvm` and follow steps in `brew info llvm`
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]
```
