### ISSUE TITLE
Chapter 5 - Digital Ocean: Failed to execute query: PoolTimedOut

### ISSUE THREAD

**Issue by thebrandonlucas** [LukeMathWalker/zero-to-production#243]
Hello, I'm having trouble getting the `POST /subscriptions` endpoint to work with `curl`, it returns a `500`:

```
curl --request POST \
--data 'name=le%20guin&email=ursula_le_guin%40gmail.com' \
https://<zero2prod-digital-ocean-url>/subscriptions --verbose
```

`GET /health_check` works fine and returns `200`.

The runtime logs in Digital Ocean have this error:
`[SAVING NEW SUBSCRIBER DETAILS IN THE DATABASE - EVENT]: Failed to execute query: PoolTimedOut`.

It looks like some others have had this issue before me, but none seem to apply to my situation:
- #150 tries to downgrade to use `Config` crate version `0.11`. I am using `0.13` as in the current version of the book. Also, downgrading causes errors with the `.separator()` method in `config::Environment`.
- I'm using postgres version `12` as in the book, and [this comment](https://github.com/LukeMathWalker/zero-to-production/issues/200#issuecomment-1491447036) seems to imply that only version `12` should work anyway.
- I double-checked that I am using the prefix separator that was causing the issue in #155.
- I have disabled [Trusted Sources](https://docs.digitalocean.com/products/databases/postgresql/how-to/secure/#firewalls).

I have deleted and recreated the app, re-run `DATABASE_URL=<connection-string> sqlx run migrate`, to no avail.

Here is the relevant part of `spec.yaml`:
```
name: zero2prod
region: fra
services:
  - name: zero2prod
   [...]
    envs:
      - key: APP_DATABASE__USERNAME
        scope: RUN_TIME
        value: ${newsletter.USERNAME}
      - key: APP_DATABASE__PASSWORD
        scope: RUN_TIME
        value: ${newsletter.PASSWORD}
      - key: APP_DATABASE__HOSTNAME
        scope: RUN_TIME
        value: ${newsletter.HOSTNAME}
      - key: APP_DATABASE__PORT
        scope: RUN_TIME
        value: ${newsletter.PORT}
      - key: APP_DATABASE__DATABASE_NAME
        scope: RUN_TIME
        value: ${newsletter.DATABASE}
databases:
  - engine: PG
    name: newsletter
    num_nodes: 1
    size: db-s-dev-database
    version: "12"
```

Here is my `get_configuration()`:
```
pub fn get_configuration() -> Result<Settings, config::ConfigError> {
    let base_path = std::env::current_dir().expect("Failed to determine the current directory");
    let configuration_directory = base_path.join("configuration");

    // Detect the running environment.
    // Default to `local` if unspecified.
    let environment: Environment = std::env::var("APP_ENVIRONMENT")
        .unwrap_or_else(|_| "local".into())
        .try_into()
        .expect("Failed to parse APP_ENVIRONMENT");
    let environment_filename = format!("{}.yaml", environment.as_str());
    let settings = config::Config::builder()
        .add_source(config::File::from(
            configuration_directory.join("base.yaml"),
        ))
        .add_source(config::File::from(
            configuration_directory.join(&environment_filename),
        ))
        .add_source(
            config::Environment::with_prefix("APP")
                .prefix_separator("_")
                .separator("__"),
        )
        .build()?;

    settings.try_deserialize::<Settings>()
}
```

Thanks for the awesome book. I've been learning a ton and am excited to move forward, any help would be appreciated.
