### ISSUE TITLE
Chapter 1.4: Git hooks c.f. CI/CD pipelines

### ISSUE THREAD

**Issue by bbros-dev** [LukeMathWalker/zero-to-production#56]
Thank you for taking the time and making the effort to write this book.

I was a little surprised to find no mention of Git hooks c.f. CI/CD services for fast feedback activities like formatting and linting - usually run via a pre-commit hook. 
This definitely smooths the review process, and stops the CI/CD from breaking for trivia that should not make its way into a commit - IMO.

The use of [left-hook (go binary)](https://github.com/Arkweid/lefthook), husky or pre-commit ensure the hook configuration and scripts reside in the project.

I wonder if longer compile times could make git hooks appear to be as fast/slow as external CI/CD services?
Any other reasons to stay clear of git hooks?

**Comment by bbros-dev** [comment]
In case this is of interest, using lefthook, crate checking is likely best done pre-push:

```yaml
# lefthook.yml
pre-push:
  commands:
    cargo-audit:
      tags: backend security
      run: cargo audit
    cargo-deny:
      tags: backend security
      run: cargo deny check
pre-commit:
  parallel: false
  commands:
    cargo-format:
    tags: backend style
    run: cargo fmt -- --backup --check --files-with-diff
```
